<fieldset id="cd-mcpl-fieldset" class="rows">
    <legend>Music CD details</legend>
    <ol id="publication-mcpl-fields">
        <li>
            <label for="title">Title:</label>
            <input type="text" name="title" id="title" value="[% whole.value.other.title %]" />
        </li>
        <li>
            <label for="artist">Artist:</label>
            <input type="text" name="artist" id="artist" value="[% whole.value.other.artist %]" />
        </li>		
        <li>
            <label for="year">Year:</label>
            <input type="text" name="year" id="year" value="[% whole.value.other.year %]" />
        </li>	
        <li>
            <label for="asin">ASIN:</label>
            <input type="text" name="asin" id="asin" value="[% whole.value.other.asin %]" />
        </li>	

    </ol>
</fieldset>
