<fieldset id="dvd-mcpl-fieldset" class="rows">
    <legend>DVD details</legend>
    <ol id="publication-mcpl-fields">
        <li>
            <label for="title">Title:</label>
            <input type="text" name="title" id="title" value="[% whole.value.other.title %]" />
        </li>
        <li>
            <label for="year">Year:</label>
            <input type="text" name="year" id="year" value="[% whole.value.other.year %]" />
        </li>	
        <li>
            <label for="other_info">Other Info:</label>
            <input type="text" name="other_info" id="other_info" value="[% whole.value.other.other_info %]" />
        </li>

    </ol>
</fieldset>
