<fieldset id="vgame-mcpl-fieldset" class="rows">
    <legend>Video Game details</legend>
    <ol id="publication-mcpl-fields">
        <li>
            <label for="title">Title:</label>
            <input type="text" name="title" id="title" value="[% whole.value.other.title %]" />
        </li>
        <li>
            <label for="console">Console:</label>
            <input type="text" name="console" id="console" value="[% whole.value.other.console %]" />
        </li>

    </ol>
</fieldset>
